name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: 'package-lock.json'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy
        run: ./deploy/deploy.sh
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Create timestamp
        id: create_timestamp
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "current date $CURRENT_DATE"
          echo "current_timestamp=$CURRENT_DATE" >> "$GITHUB_OUTPUT"
      - name: Create image
        run: echo "Create docker image with tag ${{ steps.create_timestamp.outputs.current_timestamp }}"
      - name: Deploy tag
        run: echo "Deploy tag ${{ steps.create_timestamp.outputs.current_timestamp }} to environment"