name: Advanced action skills
on:
  push:
jobs:
  deploy:
    if: contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Run on deploy comment
        run: |
          echo "This is executed from the main branch"