name: Deploy to Production
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy
      run: |
        chmod +x deploy/deploy.sh
        ./deploy/deploy.sh
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}